name = "memorygame"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
[env.production]
nodejs_version = "18.x"
command = "npm run build"